### ISSUE TITLE
Issue with schemaAgency identifier

### ISSUE THREAD

**Issue by amiika** [SEMICeu/ADMS#6]
Was schemaAgency intentionally renamed? There is now issue with the identifier and it is called and referred as schemeAgency from multiple vocabularies.

For example https://semiceu.github.io/Core-Business-Vocabulary/releases/2.1.0/context/core-business-ap.jsonld refers it as schemeAgency.

URIs should not change.

**Comment by bertvannuffelen** [comment]
@amiika In the [Changelog](https://github.com/SEMICeu/ADMS/blob/main/releases/2.00/CHANGELOG.md) we mention the change as discussed in issue #4. 

This issue has also been discussed in the [webinar](https://semiceu.github.io/uri.semic.eu-generated/ADMS/releases/2.00/#meeting-minutes)

As said in the discussion of the issue: this is because in the past there was an error made. And thus depending on which source you had been 'considering' the truth, you ended up in another URI. That is resolved now. But yes, for those who followed the typo in the RDF distribution have to adapt.

On the use of the URI in core business: this should be changed there.

**Comment by EmidioStani** [comment]
This issue can be closed, it is resolved in [Core Person 2.1.1](https://semiceu.github.io/Core-Person-Vocabulary/releases/2.1.1/#Identifier.schemaagency), [Core Business 2.2.0](https://semiceu.github.io/Core-Business-Vocabulary/releases/2.2.0/#Identifier.schemaagency) and [CPOV 2.1.1](https://semiceu.github.io/CPOV/releases/2.1.1/#Identifier.schemaagency)
